base_path: /path/to/training/data/
ion_dictionary_path: /path/to/training/data/ion_dictionary.txt
wandb_save_dir: /path/to/wandb_output
dataset_path: datasets/
position_path: txt_pos/
label_path: labels/
saved_model_path: saved_model/

weights:
restart:
transfer:

seq_len: 40
chlim: 
   - 1
   - 8

model_config:
   embedsz: 256
   blocks: 9
   head:
      - 16
      - 16
      - 64
   units: None
   filtlast: 512
   learn_ffn_embed: False
   CEembed: True
   drop: 0.1
   coefs: 4
   knots: [6,13,20,27,34,41,48,55]

root_int:
lr: 3e-4
epochs: 100
steps: 1000000
batch_size: 100
test_batch_size: 500
lr_decay_start: 3
lr_decay_rate: 0.85
svwts: all
num_workers: 4

